# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  IS_TEST: "True"
  DOCKER_BUILDKIT: 1
  DB_URL: "mysql://root:test@127.0.0.1/test_heliotrope"

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Test
    jobs:
    - job: pytest
      strategy:
        matrix:
          Python39:
            python.version: '3.9'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
      
      - script: |
          sudo apt install -y mariadb-server mariadb-client
          sudo mysql -uroot -proot -e "use mysql; update user set authentication_string=PASSWORD('test') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
          sudo mysql -uroot -ptest -e 'create database test_heliotrope;'
        displayName: 'Install mariadb and setup'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          pip install pytest pytest-azurepipelines sanic-testing pytest-cov
          pytest --cov=./
        displayName: 'Test with pytest and generate coverage report'

      - script: |
          bash <(curl -s https://codecov.io/bash)
        displayName: 'Upload coverage to Codecov'
  
  - stage: Docker
    dependsOn: Test
    jobs:
      - job: Build
        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: Heliotrope
            command: build
            Dockerfile: ./Dockerfile
