# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  IS_TEST: "True"
  DOCKER_BUILDKIT: 1
  DB_URL: "mysql://root:test@127.0.0.1/test_heliotrope"
  HIYOBOT_SECRET: "test"
  MONGO_DB_URL: "mongodb://root:test@127.0.0.1"

trigger:
- master

resources:
  containers:
    - container: mariadb
      image: mariadb:latest
      options: -p 127.0.0.1:3306:3306
      env:
        MYSQL_DATABASE: test_heliotrope
        MYSQL_ROOT_PASSWORD: test
        containers:
    - container: mongo
      image: mongo:latest
      env:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: test
      ports:
        - 27017:27017
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Test
    jobs:
    - job: pytest
      strategy:
        matrix:
          Python39:
            python.version: '3.9'

      services:
        mariadb: mariadb
        mongo: mongo

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: |
          mongo -u root -p test --eval "db.getSiblingDB('test').createCollection('test_collection')"
        displayName: 'make mongodb collection'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          pip install pytest pytest-azurepipelines sanic-testing pytest-cov
          pytest --cov=./
        displayName: 'Test with pytest and generate coverage report'

      - script: |
          bash <(curl -s https://codecov.io/bash)
        displayName: 'Upload coverage to Codecov'
  
  - stage: Docker
    dependsOn: Test
    jobs:
      - job: Build
        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: Heliotrope
            command: build
            Dockerfile: ./Dockerfile
