# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Type checker

on:
  push:
    branches: [ v5 ]
  pull_request:
    branches: [ v5 ]

jobs:
  type_cheking:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install pyright
      run: sudo npm install -g pyright
    - name: Install Dependencies
      run: |
         pip install mypy
         pip install -r requirements.txt
    - name: Mypy cheking
      run: mypy ./heliotrope --strict
    - name: pyright checking
      run: pyright ./heliotrope --lib --outputjson
         
    
    
